""" This module provide task manager.

    The task in Amber is a execution thread.
    
    Copyright (C) 2008 ~ 2012. All Rights Reserved.
    The contents of this file are subject to the Mozilla Public License
    Version 1.1 (the "License"); you may not use this file except in
    compliance with the License. You may obtain a copy of the License at
    http://www.mozilla.org/MPL/

    Software distributed under the License is distributed on an "AS IS"
    basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
    License for the specific language governing rights and limitations
    under the License.

    Initial Developer: Lu Ken <bluewish.ken.lu@gmail.com>
"""   

__author__   = "Lu Ken <bluewish.ken.lu@gmail.com>"
__revision__ = "$Revision: 1 $"

#======================================  External Libraries ========================================
import wx
import os
from wx.lib.embeddedimage import PyEmbeddedImage

#============================================== Code ===============================================
#----------------------------------------------------------------------
# This file was generated by N:\tools\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

ToasterBoxbackground = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAAA3NCSVQICAjb4U/gAAADEklE"
    "QVR4nO2b25aDIAxFYRb//8udh96wJSUnEBIx+20cQNylFDyaUsAmp5Rut5t1N05AzvnPug9n"
    "ImQBhCyAkAUQsgBCFkDIAghZACELIGQBhCyAkAUQsgBCFkDIAghZACELIGQBhCyAkAUQsgBC"
    "FkDIAghZACELIGQBhCyAkAUQsgBCFkDIAiiJ/XxWzlm5M94p/KIjz7ztIbqklD4caFyWWLQr"
    "y42RNfLM5PQrczWcS0pSPa2e7C268TVktSWr9q7cYHZ7QzRFAxP8oa2BfuTZw2/ZcL4vHch6"
    "Kh+atOLQcE4TRFcjq1WP29YS0aOihkXf56wbfmHHGtcQXaRtvWu4Eq06b9BLB/ZpF4r+Kv51"
    "btXhTC8dvo4CF6Yl2ng4I3vDgaLca/M4nN81Vu0NpeUcDOd3jcac1WiL3Q/LXzF90byvIbvL"
    "e4t+rLPQrgKl9UUvmzfKz/8y2zIW3S6lILraG/Lb+jy6SDT2mYhF06fpzFnMJViT6aLNh/Nj"
    "6bBuuSAWbTSc69KPpYNgJy08M4+GCaPhXJcunwdQsrNbycDRT7qigdvK7bbGVPm6ldw7qrM3"
    "/GK6aJN5o5FIa0R180eQhehWbugpqlOZEKWNCtMdir1FD+SGs3EV8dN7w9+dvF7yTNEZWddM"
    "nilEe0Me502eKZbvDXn4FP3cGw70w5Vo1Yi/HP/s1b5G8kzRXTpcMXmmUN0bKoo2Gc6N28qu"
    "ojpXw3nsmdJNk2fq3LP3hgPl/Is+fg3tAtF0hoi/9Isw29ooeaZg7A2l/QAKOkueKTqLUvOo"
    "rl9qoejHnOUqecZKKyTPVMGfz5Q6iOrMLdcFJywd9kueKYZzwzF8Js/UGdgvOl0peabaYj9T"
    "eqXkmWLJ+4ZnS54pjPaGLfyLBl4oP7S1d8RPzBvS9w23Tp6pFuftDdn4T54pqqWDy6iuxnw4"
    "V7mhm+SZblLOFNHi9w2rthSs+FqXPUWr7Q15+EyeKYiXBq6dPFO8bv5F8tzntXSI5LnPlL3h"
    "bskzBe8WjcdM1GDe4N3800+eWd0gilvOGwHFP1gtOyUKg9+8AAAAAElFTkSuQmCC")
getToasterBoxbackgroundData = ToasterBoxbackground.GetData
getToasterBoxbackgroundImage = ToasterBoxbackground.GetImage
getToasterBoxbackgroundBitmap = ToasterBoxbackground.GetBitmap
getToasterBoxbackgroundIcon = ToasterBoxbackground.GetIcon


def getlogoBitmap():
    return wx.Bitmap(os.path.join(wx.GetApp().GetPath(), 'images', 'logo_blue_background.png'))
    
app_icon_16_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAADJViUEAAAABHNCSVQICAgIfAhkiAAAAYJJ"
    "REFUKJGV0stKW1EUxvH/Sk2kVmqoxhCDVttcUPBCxYBaQQWJjTNx1FFfwaGP4At00EFHFSdO"
    "1IEIXrAtiq0kUsHeUDDheElNNMfaJJpkOwoU8ejxm67vt9cabOEeUUpZCL8fQ496aX4zXnIf"
    "zO+518S/dYEUONMaLKa36rqDbKqSxuG35C9t1HcvmsYcfg7iDizxL1GD/9UHEcmawiq+/QKA"
    "/HkpqagXz9AkwJ1YKSXsh/uoeL6FttlLbee8iORMYfY+hrDZ0lyeVmGxZXEHloqjW7FSqpzk"
    "TguO5nVSez6ePPsuIsoUZndxkEcOjb8JJwDujuX/x4ZY6bqDQu4BZa4YmaQT6+OUiORNYZKR"
    "AH+2A+QyDynkLXiD09crxvgiXYG9/gcHX/spd8VE5Px6xfh75nQ7VvsxnqEJqfZFbqqUACht"
    "o4fYWghX2yp1LxeIrgyQSZ/gGZgSkYLR+6LmRmeo8kdoGnmH9qWXxK9Wato/ydOeWcOrilFH"
    "P1vvLBnkCgzMgvixy99WAAAAAElFTkSuQmCC")
getapp_icon_16_16Data = app_icon_16_16.GetData
getapp_icon_16_16Image = app_icon_16_16.GetImage
getapp_icon_16_16Bitmap = app_icon_16_16.GetBitmap
getapp_icon_16_16Icon = app_icon_16_16.GetIcon

#----------------------------------------------------------------------
# This file was generated by M:\tools\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

StopEnable = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAYAAACprHcmAAAABHNCSVQICAgIfAhkiAAAAJtJ"
    "REFUGJWNkSESg0AMRR8zK5CRlSsre4QeAYlEVnIcZCUSWdkjICtXrvwyjgqwKX0zcW/eZJLm"
    "M02b3gtn2L0j6TVzGx6n8vqcSAA4aJ7jat8DkJBTJMzjapFAfpQB/Id9kORwLQWXQulSCoKj"
    "LN8nQo4ckgmwdp8IazFB8lqpOWNtLNec8Vr3NbIZjPGtDahAsw7jpuWPD3YdX0lPPsXhA0Xq"
    "AAAAAElFTkSuQmCC")
getStopEnableData = StopEnable.GetData
getStopEnableImage = StopEnable.GetImage
getStopEnableBitmap = StopEnable.GetBitmap
getStopEnableIcon = StopEnable.GetIcon

#----------------------------------------------------------------------
# This file was generated by M:\tools\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

stopdisable = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAYAAACprHcmAAAABHNCSVQICAgIfAhkiAAAAG9J"
    "REFUGJWNziEOwzAQRNFfqWBgYKCh738CHyPQcGHgsBY4VkK87af7NNpXa+3Dn70B6r7/hEfE"
    "wAC99yUspdzLpw1er572jUeJvhrYxpl9LttOl/3EkgAtsSSwrzekzI77xJvEVmuiIeYbR0QK"
    "Z1+48CYBjy0PkAAAAABJRU5ErkJggg==")
getStopDisableData = stopdisable.GetData
getStopDisableImage = stopdisable.GetImage
getStopDisableBitmap = stopdisable.GetBitmap
getStopDisableIcon = stopdisable.GetIcon


StopHover = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAWCAYAAADafVyIAAAABHNCSVQICAgIfAhkiAAAAPhJ"
    "REFUSIntla1OBTEQhb9erlhZiawExyPwCJVXIm/AIDHA7jMQCJKgViKRSCQOW1k5ctwgNjja"
    "wg0VJJxk1Dmdrz9p68zM6KRpmlgBrPbWrkcBC6Cn/gFNrWvm+92tyctTs4k/jhyenrkfA+R5"
    "5uhk2wS8PdwXvSoAAAWZ56LtN5vq8DpAlCSC13IkiYCUA+0VAGiF0FD9DBQOUkJFipn9lCi7"
    "31mBaHULEK3aVYAXwA9LFUPDktsFoDmTQ8APZUAOAc15NwBA8B7Oy3fBA+X2rS2KkdftRWsO"
    "+Bjh8eZLz5mZfb7dv63rq0v7+69pd4Abx7Hbpw/wAbG1Tc5r7cBCAAAAAElFTkSuQmCC")
getStopHoverData = StopHover.GetData
getStopHoverImage = StopHover.GetImage
getStopHoverBitmap = StopHover.GetBitmap
getStopHoverIcon = StopHover.GetIcon


viewbook = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAABHNCSVQICAgIfAhkiAAAASdJ"
    "REFUKJGdUkFqwzAQHFnuD3qo/xCCFegDmkupii7+gskvTKCpv5BTCS2mvuZgI4W+IWBdcveh"
    "BfsV2R5aiRrTNmRhQKx2md2ZZSzgOCfC/wru7m/JvXf6jfkPFvA/IZUkF1JJcvngVLb+o0e+"
    "yn0u/K0QAHSlYWoDdsHQ7BtElxHMzoCBYzCSrjQREaWLlIiIdKVJxIKkkoQQHqNRpZIAgK7v"
    "YGqDbJkhX+WIrqIvPY6csSNnA3GcCLrSnklXmtJF6lkGcD4+5g8EAGIisK23SFSC9dMa3XsH"
    "e7DwTM6NnwcQT6c0u54hUQkAwB4s2rbF5nkzavQ7vr4UZA8Wzb5BtswGtoiJGHvFAo6yKAkh"
    "qCxKcvs6BUUsxvsF33bMb+a+6WSce+Sfv/mPDc/7L+gAAAAASUVORK5CYII=")
getviewbookData = viewbook.GetData
getviewbookImage = viewbook.GetImage
getviewbookBitmap = viewbook.GetBitmap
getviewbookIcon = viewbook.GetIcon

def getFrameBitmap():
    path = os.path.join(wx.GetApp().GetPath(), 'images', 'app_icon_16_16.png')
    return wx.Bitmap(path)